#!/bin/bash
if [[ $1 == "" ]]; then
  echo "what is your username?"
  read user
else
  user=$1
fi
declare -a names=("blum" "lovelace" "cook" "dean" "hopper" "von\ ahn" "sweeney"
                  "yao" "cerf" "hamilton" "mouton" "pnueli" "corbato" "liskov"
                  "curry" "easley" "kruskal" "church")

while [[ $? != 0 ]]; do
  length=${#names[@]}
  candidateIndex=$(($RANDOM * $length / 32000))  # %RANDOM is on (0...32000)
  echo "connecting to ${names[$candidateIndex]}"
  exec ssh -Y "$user@${names[$candidateIndex]}.cs.haverford.edu"

  if [[ $? != 0 ]]; then
    echo "failed to connect... Let's try another one!"
    declare -a new_names
    for name in ${names[@]}; do
      if [[ $name != ${names[$candidateIndex]} ]]; then
        new_names+=name
      fi
    done
    names=new_names
    unset new_names
  fi
done

# Andy Dupree, 2021
